package:
  name: "ifaa"
  version: "0.0.9000"

source:
  git_url: https://github.com/lovestat/IFAA
  git_rev: v0.0.9002

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - joblib >=0.10.3
    - numpy >=1.22.3
    - scipy >=1.8.0
    - pandas >=1.4.1
    - glmnet_py >=1.0.2
    - matplotlib >=3.5.1
    - tqdm >=4.63.1
    - statsmodels >=0.13.2

about:
  home: https://github.com/lovestat/IFAA
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Robust association identification and inference for absolute abundance in microbiome analyses"

extra:
  recipe-maintainers:
    - Shangchen Song 
