package:
  name: "ifaa"
  version: "0.0.9000"

source:
  url: https://files.pythonhosted.org/packages/c4/b1/0840f69317d57fa8b1381a97a6dfd44cda7003f40290a5823f8b2226deab/IFAA-0.0.9002.tar.gz
  sha256: ac6a9c6c10f425cd4d44ca2524e7e9089ebf9502b797895e7b5576b57d1bd77f

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - joblib >=0.10.3
    - numpy >=1.22.3
    - scipy >=1.8.0
    - pandas >=1.4.1
    - glmnet_py >=1.0.2
    - matplotlib >=3.5.1
    - tqdm >=4.63.1
    - statsmodels >=0.13.2

about:
  home: https://github.com/lovestat/IFAA
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Robust association identification and inference for absolute abundance in microbiome analyses"

extra:
  recipe-maintainers:
    - Shangchen Song
