package:
  name: "ifaa"
  version: "0.0.9000"

source:
  url: https://files.pythonhosted.org/packages/d0/d5/7902f323bd3a36b0050825d6f1b3c03a93cbf79e1fb7001e6e07f245b07c/IFAA-0.0.9004.tar.gz
  sha256: e086496c69a9c89a30e4d57efeb10d2f27d40abfb765067ff8fa18981f0eb49f

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - joblib >=0.10.3
    - numpy >=1.22.3
    - scipy >=1.8.0
    - pandas >=1.4.1
    - glmnet_py >=1.0.2
    - matplotlib >=3.5.1
    - tqdm >=4.63.1
    - statsmodels >=0.13.2

about:
  home: https://github.com/lovestat/IFAA
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Robust association identification and inference for absolute abundance in microbiome analyses"

extra:
  recipe-maintainers:
    - Shangchen Song 
